### ISSUE TITLE
Add missing timezone

### ISSUE THREAD

**Issue by mminhlequang** [kyle-seongwoo-jun/flutter_timezone_to_country#2]
"Asia/Saigon": "VN",

**Comment by kyle-seongwoo-jun** [comment]
Hi @mminhlequang.

I searched for `"Asia/Saigon"` on the internet, but it appears to have been replaced by `"Asia/Ho_Chi_Minh"`, which this library supports. This library generates code from the IANA (Internet Assigned Numbers Authority) database, so I don't plan to support `"Asia/Saigon"`. I'm sorry for any inconvenience. 

Happy coding!
